# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО врача')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специальность')),
                ('info', models.TextField(verbose_name='Информация о враче')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема ')),
                ('time', models.CharField(max_length=9, verbose_name='Время приема ')),
                ('patient_name', models.CharField(max_length=200, verbose_name='ФИО пациента')),
                ('patient_info', models.TextField(verbose_name='Информация о пациенте ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolnicaapp.Doctor', verbose_name='Лечащий врач ')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
            },
        ),
    ]
