# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolnicaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='time',
            field=models.TimeField(verbose_name='Время приема '),
        ),
    ]
